name: gg_create_package
description: The audanika developer command line
version: 0.0.1
repository: https://github.com/inlavigo/gg_create_package.git

publish_to: none

environment:
  sdk: ">=3.3.0<4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.4.2
  recase: ^4.1.0
  dart_style: ^2.3.4
  yaml_edit: ^2.1.1
  gg_args: ^1.0.3
  gg_log: ^1.0.0
  gg_console_colors: ^2.0.2

dev_dependencies:
  gg_capture_print: ^1.0.2
  gg_install_gg: ^1.0.1
  lints: ^3.0.0
  pana: ^0.22.1
  test: ^1.24.0

executables:
  gg_create_package: