name: gg_create_package
description: A command line tool to create dart packages
version: 4.0.0
repository: https://github.com/ggsuite/gg_create_package.git

environment:
  sdk: ">=3.3.0<4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.4.2
  recase: ^4.1.0
  dart_style: ^2.3.4
  yaml_edit: ^2.1.1
  gg_args: ^2.0.2
  gg_log: ^1.0.0
  gg_console_colors: ^2.0.2
  pubspec: ^2.3.0

dev_dependencies:
  gg_capture_print: ^1.0.2
  lints: ^3.0.0
  test: ^1.24.0

executables:
  gg_create_package: