name: aud_cli_create_dart_package
description: The audanika developer command line
version: 1.0.0
repository: https://github.com/inlavigo/aud_cli_create_dart_package

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  args: ^2.4.2
  colorize: ^3.0.0
  recase: ^4.1.0
  dart_style: ^2.3.4

dev_dependencies:
  lints: ^3.0.0
  pana: ^0.21.45
  test: ^1.24.0
  yaml: ^3.1.2
  dart_ping: ^9.0.1
